---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/vsphere-cpi-release}
inputs:
  - name: bosh-cpi-src
  - name: version-semver
  - name: bosh-cli
outputs:
  - name: dev-artifacts
run:
  path: bosh-cpi-src/ci/tasks/build-candidate.sh
