platform: linux
image_resource:
  { type: docker-image, source: { repository: vcpici/vcpi-main } }

inputs:
  - name: certification
  - name: environment
  - name: bosh-deployment
  - name: bosh-release
  - name: cpi-release
  - name: stemcell
  - name: bosh-cpi-src

outputs:
  - name: director-config

run:
  path: bosh-cpi-src/ci/tasks/prepare-director.sh