---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/vsphere-cpi-release}
inputs:
  - name: bosh-cpi-src
  - name: stemcell
  - name: bosh-cli
outputs:
  - name: dummy # dummy output to avoid sending the entire task over the network
run:
  path: bosh-cpi-src/ci/tasks/run-lifecycle.sh
params:
  RSPEC_FLAGS:                             ""
  BOSH_VSPHERE_VERIFY_LIMITED_PERMISSIONS: true
