platform: linux
image_resource:
  { type: docker-image, source: { repository: vcpici/vcpi-main } }

inputs:
  - name: certification
  - name: director-state
  - name: bosh-cpi-src
  - name: environment

run:
  path: bosh-cpi-src/ci/tasks/teardown.sh
