jobs:
  - name: pyvmomi_to_ruby-tests
    plan:
      - get: bosh-cpi-src
        trigger: true
      - task: test
        file: bosh-cpi-src/ci/tasks/test-pyvmomi_to_ruby.yml

  - name: build-candidate
    serial: true
    plan:
      - aggregate:
        - get: bosh-cpi-src
          trigger: true
        - get: version-semver
          trigger: false
          params:
            bump: patch
      - put: version-semver
        params:
          file: version-semver/number
      - task: build
        file: bosh-cpi-src/ci/tasks/build-candidate.yml
      - put: bosh-cpi-artifacts
        params:
          file: 'dev-artifacts/*.tgz'

  - name: lock-and-extend-6.5
    plan:
      - get: bosh-cpi-src
        trigger: true
        passed: [build-candidate]
      - do:
        - put: nimbus-environments-6.5
          params: {acquire: true}
        - task: extend-lease-6.5
          file: bosh-cpi-src/ci/tasks/extend-lease.yml
          params:
            DBCUSER: {{dbc_user}}
            DBCHOST: {{dbc_host}}
            DBC_SSH_KEY: {{dbc_key}}
          on_failure:
            put: nimbus-environments-6.5
            params : {release: nimbus-environments-6.5}
        attempts: 4


  - name: lifecycle-6.5
    serial: true
    plan:
      - aggregate:
        - {trigger: false,  passed: [build-candidate], get: bosh-cpi-artifacts}
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-src}
        - {trigger: true, passed: [lock-and-extend-6.5], get: nimbus-environments-6.5}
        - get: stemcell
      - task: test
        file: bosh-cpi-src/ci/tasks/run-lifecycle.yml
        params:
          RSPEC_FLAGS: "--tag ~nsx_vsphere --tag ~disk_migration"
          NSXT_SKIP_SSL_VERIFY: "true"
        on_failure:
          put: nimbus-environments-6.5
          params : {remove: nimbus-environments-6.5}

  - name: unlock-6.5
    plan:
      - {trigger: true, passed: [lifecycle-6.5], get: nimbus-environments-6.5}
      - put: nimbus-environments-6.5
        params : {release: nimbus-environments-6.5}

  - name: lock-and-extend-6.0
    plan:
      - get: bosh-cpi-src
        trigger: true
        passed: [build-candidate]
      - do:
        - put: nimbus-environments-6.0
          params: {acquire: true}
        - task: extend-lease-6.0
          file: bosh-cpi-src/ci/tasks/extend-lease.yml
          params:
            DBCUSER: {{dbc_user}}
            DBCHOST: {{dbc_host}}
            DBC_SSH_KEY: {{dbc_key}}
          on_failure:
            put: nimbus-environments-6.0
            params : {release: nimbus-environments-6.0}
        attempts: 4

  - name: lifecycle-6.0
    serial: true
    plan:
      - aggregate:
        - {trigger: false,  passed: [build-candidate], get: bosh-cpi-artifacts}
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-src}
        - {trigger: true, passed: [lock-and-extend-6.0], get: nimbus-environments-6.0}
        - get: stemcell
      - task: test
        file: bosh-cpi-src/ci/tasks/run-lifecycle.yml
        params:
          RSPEC_FLAGS: "--tag ~nsx_vsphere --tag ~nsx_two_only"
          NSXT_SKIP_SSL_VERIFY: "true"
        on_failure:
          put: nimbus-environments-6.0
          params: {release: nimbus-environments-6.0}

  - name: unlock-6.0
    plan:
      - {trigger: true, passed: [lifecycle-6.0], get: nimbus-environments-6.0}
      - put: nimbus-environments-6.0
        params : {release: nimbus-environments-6.0}

  - name: lock-and-extend-bats
    plan:
      - get: bosh-cpi-src
        trigger: true
        passed: [build-candidate]
      - do:
        - put: nimbus-environments-6.5
          params: {acquire: true}
        - task: extend-lease-6.5
          file: bosh-cpi-src/ci/tasks/extend-lease.yml
          params:
            DBCUSER: {{dbc_user}}
            DBCHOST: {{dbc_host}}
            DBC_SSH_KEY: {{dbc_key}}
          on_failure:
            put: nimbus-environments-6.5
            params : {release: nimbus-environments-6.5}
        attempts: 4

  - name: bats
    serial: true
    plan:
      - aggregate:
        - {get: cpi-release,              trigger: false, resource: bosh-cpi-artifacts, passed: [build-candidate]}
        - {get: environment,              trigger: true,  passed: [lock-and-extend-bats], resource: nimbus-environments-6.5 }
        - {get: bosh-release,             trigger: false, resource: old-bosh-release}
        - {get: stemcell,                 trigger: false, resource: old-stemcell}
        - {get: certification,            trigger: false}
        - {get: bosh-deployment,          trigger: false}
        - {get: bats,                     trigger: false}
        - {get: bosh-cli,                 trigger: false}
        - {get: bosh-cpi-src,             trigger: false, passed: [build-candidate]} # Passthrough
      - task: prepare-director
        file: bosh-cpi-src/ci/tasks/prepare-director.yml
      - do:
        - task: deploy-director
          file: bosh-cpi-src/ci/tasks/deploy-director.yml
        - task: run-bats
          file: bosh-cpi-src/ci/tasks/run-bats.yml
          params:
            BAT_INFRASTRUCTURE: vsphere
            BAT_NETWORKING:     manual
            BAT_RSPEC_FLAGS:    "--tag ~vip_networking --tag ~dynamic_networking --tag ~root_partition --tag ~raw_ephemeral_storage"
            STEMCELL_NAME:      bosh-vsphere-esxi-ubuntu-trusty-go_agent


  - name: unlock-bats
    plan:
      - {trigger: true, passed: [bats], get: nimbus-environments-6.5}
      - put: nimbus-environments-6.5
        params : {release: nimbus-environments-6.5}

  - name: delivery
    plan:
    - aggregate:
      - {trigger: true, passed: [lifecycle-6.0, lifecycle-6.5, bats], get: bosh-cpi-artifacts}
      - {trigger: false, passed: [lifecycle-6.0, lifecycle-6.5, bats], get: bosh-cpi-src}
    - put: tracker-output
      params:
        repos:
        - bosh-cpi-src

  - name: promote-candidate
    serial: true
    plan:
    - aggregate:
      - {trigger: false, passed: [lifecycle-6.0, lifecycle-6.5, bats], get: bosh-cpi-artifacts}
      - {trigger: false, passed: [lifecycle-6.0, lifecycle-6.5, bats], get: bosh-cpi-src}
      - {trigger: false, get: release-version-semver, params: {bump: major}}
      - {trigger: false, get: bosh-cli}
    - task: promote
      file: bosh-cpi-src/ci/tasks/promote-candidate.yml
      params:
        AWS_ACCESS_KEY_ID:     "s3_vsphere_cpi_blobwriter_access_key"
        AWS_SECRET_ACCESS_KEY: "s3_vsphere_cpi_blobwriter_secret_key"
    - put: bosh-cpi-src-out
      params: {repository: updated-repo/, rebase: true, tag_prefix: "v", tag: integer-version/tag-file}
    - put: release-version-semver
      params: {file: release-version-semver/number}

resources:
  - name: release-version-semver
    type: semver
    source:
      key:               release-current-version
      bucket:            {{s3_vsphere_cpi_bucket}}
      access_key_id:     {{s3_vsphere_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vsphere_cpi_blobwriter_secret_key}}
  - name: nimbus-environments-6.5
    type: pool
    source:
      uri:          git@github.com:ktchen14/vcpi-pool.git
      branch:       master
      pool:         NJ65
      private_key:  {{vcpi-pool_deployment_key}}
  - name: nimbus-environments-6.0
    type: pool
    source:
      uri:          git@github.com:ktchen14/vcpi-pool.git
      branch:       master
      pool:         NJ60
      private_key:  {{vcpi-pool_deployment_key}}
  - name: bosh-cpi-artifacts
    type: s3
    source:
      regexp:            bosh-vsphere-cpi-([\d\.]+)\.tgz
      bucket:            {{s3_vsphere_cpi_bucket}}
      access_key_id:     {{s3_vsphere_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vsphere_cpi_blobwriter_secret_key}}
  - &bosh-cpi-src-resource
    name: bosh-cpi-src
    type: git
    source:
      uri:         git@github.com:cloudfoundry-incubator/bosh-vsphere-cpi-release.git
      branch:      {{vcpi_branch}}
      private_key: {{github_deployment_key__bosh-vsphere-cpi-release}}
  - <<: *bosh-cpi-src-resource
    name: bosh-cpi-src-out
  - name: version-semver
    type: semver
    source:
      key:               current-version
      bucket:            {{s3_vsphere_cpi_bucket}}
      access_key_id:     {{s3_vsphere_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vsphere_cpi_blobwriter_secret_key}}
  - name: stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment
      branch: master
  - name: certification
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-cpi-certification
      branch: master
  - name: old-bosh-release
    type: s3
    source:
      bucket: bosh-cpi-certification-fixtures
      regexp: precompiled-bosh-(255.8)-on-ubuntu-3232.3.tgz
      region_name: us-east-1
  - name: old-stemcell
    type: s3
    source:
      bucket: bosh-cpi-certification-fixtures
      regexp: bosh-stemcell-(3232.3)-vsphere-esxi-ubuntu-trusty-go_agent.tgz
      region_name: us-east-1
  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-linux-amd64
      bucket: bosh-cli-artifacts
      region_name: us-east-1
  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: gocli-bats
  - name: tracker-output
    type: tracker
    source:
      token: {{tracker_api_token}}
      project_id: {{tracker_project_id}}
      tracker_url: https://www.pivotaltracker.com

groups:

- name: Complete-View
  jobs:
  - pyvmomi_to_ruby-tests
  - build-candidate
  - bats
  - lock-and-extend-bats
  - unlock-bats
  - lock-and-extend-6.5
  - lifecycle-6.5
  - unlock-6.5
  - lifecycle-6.0
  - lock-and-extend-6.0
  - unlock-6.0
  - delivery

- name: Cut-Release
  jobs:
  - lifecycle-6.5
  - lifecycle-6.0
  - bats
  - promote-candidate

- name: Delivery
  jobs:
  - lifecycle-6.5
  - lifecycle-6.0
  - bats
  - delivery

- name: Unit
  jobs:
  - pyvmomi_to_ruby-tests
  - build-candidate

- name: bats
  jobs:
  - build-candidate
  - bats
  - lock-and-extend-bats
  - unlock-bats


- name: v6.5
  jobs:
  - build-candidate
  - lock-and-extend-6.5
  - lifecycle-6.5
  - unlock-6.5

- name: v6.0
  jobs:
  - build-candidate
  - lifecycle-6.0
  - lock-and-extend-6.0
  - unlock-6.0